#
# netlify.toml
#

[build]
publish = "src/dist"

# Build for "Server" target
command = "yarn build"
functions = "src/.netlify/functions-internal"

# Build for "static" target
#command = "yarn generate"
